import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import Loading from "@/app/loading.js"
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="mytheme">
          <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
        </Providers>
        </body>
    </html>
  );
}
